dist: focal

branches:
  only:
  - master

language: minimal

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-setuptools
  - pip3 install --user pycodestyle

install:
  - pip3 install --user .

before_script:
  - ./scripts/check-version

script:
  - export PATH=$HOME/.local/bin:$PATH
  - pycodestyle mtda-cli mtda/
  - mtda-cli help
