dist: focal

branches:
  only:
  - master

language: minimal

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-setuptools
  - pip3 install --user .
  - export PATH=$HOME/.local/bin:$PATH
  - mtda-cli help
