dist: focal
branches:
  only:
  - master
  - bintray
language: minimal
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y python3-pip python3-setuptools
- sudo apt-get install -y debootstrap qemu-user-static reprepro
- gem install dpl
- pip3 install --user kas pycodestyle
install:
- pip3 install --user .
before_script:
- "./scripts/check-version"
script:
- export PATH=$HOME/.local/bin:$PATH
- pycodestyle mtda-cli mtda/
- mtda-cli help
- export KAS_WORK_DIR=$PWD/build-armhf && mkdir -p $KAS_WORK_DIR
- kas build --target mtda-packages kas/mtda-nanopi-neo.yml
deploy:
- provider: pypi
  username: __token__
  password:
    secure: hNn0yGWomST9t2MS9xVtFjpm0Xs7dTnhFZ3GVJCTSsNOXBqQlNDwNQ5wZTdwz9HoU9DVJqQ25Xegu6ZCn7n3aO4TTUS6WdGfuPL1uuDvSf/S8cPlrPAEJQnVK7ghYkwo27B4Ucbr4cM9Ar/ng8ukpMTegZtUxUgFvcp+UYRPWaMF/318//CScoW2xbCJIARKcXhcR0YFY/GnYs3dey5sM95hYisGB3JAVpmgJgKPFO7f5rIBE81PGAIpHAtw77T2xgUKEHm+eu7d9FszEhlnP5P2UiX257A/aubKsee99ELSwmcMlisIlCyqRW5uyme/DdCCGWwWGUipQaNJ/+Hg0u8oywkLOaAI6Nvs36MKgwhe5c0ezX3tIR9jTo0PKT73f1yEM95jdJh1/+l7LwWdisMqi5yNZO8zXqwHqs5XjCLstlMnH0DJBvk5yf+QzePAoOdD2JraXuQNpJN1znTddrBYR5lD6ELokS1g11jlL/Zgq28+7QF3SJqevThGPFXzR3ayDScsdqep+wgB8bgYtpWwfIZxTgCLD04cqxh6b6BNoX7OurcuwYhv9RGZTTGHdKXMtoHjSRfF4/FJcjvJWytWuP3Y4BXslgdOeO7z1buflDt6I1Tpw957v4FUdJ80LoZ+y669LmAdmoeKpEN/HX5H/m2GNEeEdNioyhftLbc=
  skip_existing: true
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash scripts/upload-debs.sh
  on:
    branch: bintray
env:
  global:
    secure: i34JRoO0cpInJEWRHhPAv4GTTt+i1WcA80GQ/VQMz00MMKnkcxmavQvV8VzGyEit8GaV5anyX5yJS62q/Nf5OAxDG6ddmw1Vekslw3hisxCUJ7tGPpmemJNTVBUYkpUbH6aDD5coCFMA1mWQZLnYrRzIlsXGA55iMEb0cweLwTq9JOk2z5eXupsf7gVsSgh+nMOJDAsi1plnHnR8s0q3PuSX92F0tHQObmv2MswHHHf1/ynQulIbEHgWpZ1+BTe3a7Fi3OEs9Geoa2c7Wsv2OT6uB+UttTk0Z5i9cageogilce7IwDJ6UaOHljLvZGe61poKPniudJrtuVhXNZfpiSlqkLOmhd2vY1MTR6A7XT3GzNL34GOGpZkfaLOForoy0EPUCcrAym6l3SR0/Tw2mcvvKot3w6z2VbLUJCdcXSctpsYbA3bHmPP2nc/81ITlCVEK1yapWF76DymPQYMI6UTdbgoaTvykisdQatAbB9gozs2T71Xf+jYEsbyW5rSfKAhgXZNqogGs3wuk/+4RY/mqNRIARkMYPURtoE9i5HTODMo4Qg+DELjCDVs90LNJga5Sk785ixN766Ypc1VvM1+KpPooVvG7b9JvHjADoe67FockMh4IJ5fh7LUrJduIMkvCaesKwSa+qim9TrzY1/iPKLBC685jLtazkVyrZjk=
