# ---------------------------------------------------------------------------
# Base kas file for all configurations
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2024 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

header:
  version: 16

machine: qemuamd64
target: mtda-image

repos:
  mtda:
    layers:
      meta-isar:
  isar:
    url: https://github.com/ilbers/isar.git
    commit: 740bbf9be9f15ec46ef27f5a220b2365ee0b2f3c
    layers:
      meta:
      meta-isar:

bblayers_conf_header:
  base: |
    LCONF_VERSION = "6"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    CONF_VERSION = "1"
    ISAR_CROSS_COMPILE = "1"
  ccache: |
    USE_CCACHE = "1"
