# ---------------------------------------------------------------------------
# Base kas file for all configurations
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2022 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

header:
  version: 10

target: isar-image-base

repos:
  mtda:
    layers:
      meta-isar:
  isar:
    url: https://github.com/ilbers/isar.git
    refspec: 5f87d48f279761c2fefef1db16b4ccb5b955a364
    layers:
      meta:
      meta-isar:

bblayers_conf_header:
  base: |
    LCONF_VERSION = "6"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    CONF_VERSION = "1"
    ISAR_CROSS_COMPILE = "1"
