# ---------------------------------------------------------------------------
# Base kas file for all configurations
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2023 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

header:
  version: 10

target: mtda-image

repos:
  mtda:
    layers:
      meta-isar:
  isar:
    url: https://github.com/ilbers/isar.git
    refspec: 70c3dec0ea1d96dedc1b0aa96b5b7e64bec3939e
    layers:
      meta:
      meta-isar:

bblayers_conf_header:
  base: |
    LCONF_VERSION = "6"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    CONF_VERSION = "1"
    ISAR_CROSS_COMPILE = "1"
