# ---------------------------------------------------------------------------
# CI workflows for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2021 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: CI

on: [push]

jobs:
  lint:
    name: Check code for stylistic issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: pycodestyle
        run: |
          pip3 install --user pycodestyle
          pycodestyle mtda-cli mtda-ui mtda
  mtda-nanopi-neo-image:
    name: Debian image for running MTDA on the NanoPI NEO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages
        run: |
          export KAS_BUILD_DIR=${PWD}/build-nanopi
          ./kas-container build --target mtda-packages kas/mtda-nanopi-neo.yml
      - name: Build image
        if: github.ref == 'refs/heads/master'
        run: |
          export KAS_BUILD_DIR=${PWD}/build-nanopi
          ./kas-container build kas/mtda-nanopi-neo.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: mtda-nanopi-neo-image
          path: |
            build-nanopi/tmp/deploy/images/nanopi-neo/isar-image-base-debian-bullseye-nanopi-neo.wic.img
            build-nanopi/tmp/deploy/images/nanopi-neo/isar-image-base-debian-bullseye-nanopi-neo.wic.img.bmap
      - name: Publish .deb to Gemfury
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: |
          find build-nanopi/tmp/deploy/isar-apt -name '*.deb' -print | while read p; do
            curl -F package=@${p} https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/mtda/;
          done
  mtda-qemu-amd64-packages:
    name: Debian packages for running MTDA on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages
        run: |
          export KAS_BUILD_DIR=${PWD}/build-amd64
          ./kas-container build --target mtda-packages kas/mtda-qemu-amd64.yml
      - name: Publish .deb to Gemfury
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: |
          find build-amd64/tmp/deploy/isar-apt -name '*.deb' -print | while read p; do
            curl -F package=@${p} https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/mtda/;
          done
