# ---------------------------------------------------------------------------
# CI workflows for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2023 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ labeled ]

jobs:
  lint:
    name: Check code for issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tox
        run: |
          pip3 install --user tox
          tox -s
  mtda-nanopi-images:
    name: Debian image for running MTDA on NanoPI boards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache downloads and sstate
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('debian/changelog') }}
          path: |
            build/downloads
            build/sstate-cache
      - name: Build packages
        run: |
          ./kas-container build --target mc:nanopi-neo:mtda-packages kas/debian/mtda-nanopi-all.yml
          ./kas-container build --target mc:nanopi-r1:mtda-packages kas/debian/mtda-nanopi-all.yml
      - name: Build image
        if: github.ref == 'refs/heads/master'
        run: |
          ./kas-container build kas/debian/mtda-nanopi-all.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: mtda-nanopi-images
          path: |
            build/tmp/deploy/images/nanopi-*/mtda-image-mtda-*-nanopi-*.wic
            build/tmp/deploy/images/nanopi-*/mtda-image-mtda-*-nanopi-*.wic.bmap
      - name: Publish .deb to Gemfury
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-tc') && !contains(github.ref, '-rc')
        run: |
          find build/tmp/deploy/isar-apt -name '*.deb' -print | while read p; do
            curl -F package=@${p} https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/mtda/;
          done
  mtda-bbb-images:
    name: Debian image for running MTDA on BeagleBone Black boards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache downloads and sstate
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('debian/changelog') }}
          path: |
            build/downloads
            build/sstate-cache
      - name: Build image
        if: github.ref == 'refs/heads/master'
        run: |
          ./kas-container build kas/debian/mtda-beaglebone-black.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: mtda-nanopi-images
          path: |
            build/tmp/deploy/images/beaglebone-*/mtda-image-mtda-*-beaglebone-*.wic
            build/tmp/deploy/images/beaglebone-*/mtda-image-mtda-*-beaglebone-*.wic.bmap
  mtda-debian-qemu-amd64-packages:
    name: Debian packages for running MTDA on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache downloads and sstate
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('debian/changelog') }}
          path: |
            build/downloads
            build/sstate-cache
      - name: Build packages
        run: |
          ./kas-container build --target mtda-packages kas/debian/mtda-qemu-amd64.yml
          ./kas-container build --target qemu-packages kas/debian/mtda-qemu-amd64.yml
      - name: Publish .deb to Gemfury
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-tc') && !contains(github.ref, '-rc')
        run: |
          find build/tmp/deploy/isar-apt -name '*.deb' -print | while read p; do
            curl -F package=@${p} https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/mtda/;
          done
