# ---------------------------------------------------------------------------
# Ubuntu builds for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2022 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: Ubuntu

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ labeled ]

jobs:
  mtda-ubuntu-qemu-amd64-packages:
    name: Ubuntu packages for running MTDA on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages using Isar
        run: |
          export KAS_BUILD_DIR=${PWD}/build-amd64
          ./kas-container build --target mtda-packages kas/ubuntu/mtda-qemu-amd64.yml
          ./kas-container build --target qemu-packages kas/ubuntu/mtda-qemu-amd64.yml
      - name: Import GPG key
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Upload source packages to PPA
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          sudo apt install -y devscripts dh-python equivs
          ./scripts/build-using-ppa ${PWD}/build-amd64 focal
