# ---------------------------------------------------------------------------
# Ubuntu builds for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2022 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: Ubuntu

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ labeled ]

jobs:
  mtda-ubuntu-qemu-amd64-packages:
    name: Ubuntu packages for running MTDA on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages
        run: |
          export KAS_BUILD_DIR=${PWD}/build-amd64
          ./kas-container build --target mtda-packages kas/ubuntu/mtda-qemu-amd64.yml
          ./kas-container build --target qemu-packages kas/ubuntu/mtda-qemu-amd64.yml
